modLoader="javafml"
loaderVersion="[47,)" 
license="All Rights Reserved unless otherwise explicitly stated"

[[mods]]
modId="lasermod"
version="1.1.0"
displayName="KOWI's Laser Mod"
logoFile="logo.png"
authors="KOWI2003"
description="A Mod that adds working lasers and laser related items to minecraft"

[[dependencies.lasermod]]
    modId="forge"
    mandatory=true 
    versionRange="[47,)"  # Forge 47.x = MC 1.20.1
    ordering="NONE"
    side="BOTH"

[[dependencies.lasermod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.20.2)" # works on 1.20.1 but not 1.20.2+
    ordering="NONE"
    side="BOTH"
